"""empty message

Revision ID: 027e7dbf259b
Revises: b8eb0b3b2d95
Create Date: 2023-03-10 16:45:01.788947

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '027e7dbf259b'
down_revision = 'b8eb0b3b2d95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
