"""empty message

Revision ID: 0df9ed67294b
Revises: 027e7dbf259b
Create Date: 2023-03-10 16:46:11.495922

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '0df9ed67294b'
down_revision = '027e7dbf259b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
