"""empty message

Revision ID: 5629c517b283
Revises: 0df9ed67294b
Create Date: 2023-03-10 16:46:29.562195

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '5629c517b283'
down_revision = '0df9ed67294b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
