"""empty message

Revision ID: 665c8ab4502d
Revises: 9a1bad01716a
Create Date: 2023-03-10 16:41:37.050264

"""
from alembic import op
import sqlalchemy as sa
import ormar

# revision identifiers, used by Alembic.
revision = "665c8ab4502d"
down_revision = "9a1bad01716a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seeds",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("is_executed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seeds")
    # ### end Alembic commands ###
