"""empty message

Revision ID: 9a1bad01716a
Revises: 4fee52b11858
Create Date: 2023-03-10 15:58:47.587435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1bad01716a'
down_revision = '4fee52b11858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
