"""empty message

Revision ID: b8eb0b3b2d95
Revises: 665c8ab4502d
Create Date: 2023-03-10 16:43:15.059702

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'b8eb0b3b2d95'
down_revision = '665c8ab4502d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeds',
    sa.Column('id', sa.CHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_executed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seeds_pkey')
    )
    # ### end Alembic commands ###
