"""empty message

Revision ID: d165e2130a6c
Revises: 5629c517b283
Create Date: 2023-03-10 16:47:22.254089

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'd165e2130a6c'
down_revision = '5629c517b283'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeds',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('is_executed', sa.Boolean(), nullable=True),
    sa.Column('previous_seed_id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.ForeignKeyConstraint(['previous_seed_id'], ['seeds.id'], name='fk_seeds_seeds_id_previous_seed_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeds')
    # ### end Alembic commands ###
